from setuptools import setup, find_packages

setup(
    name='BindingRMSD',
    version='0.1.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'certifi==2024.8.30',
        'charset-normalizer==3.3.2',
        'dgl==2.4.0+cu121',
        'filelock==3.16.1',
        'fsspec==2024.9.0',
        'idna==3.10',
        'jinja2==3.1.4',
        'markupsafe==2.1.5',
        'mpmath==1.3.0',
        'networkx==3.3',
        'numpy==2.1.1',
        'packaging==24.1',
        'pandas==2.2.3',
        'pillow==10.4.0',
        'psutil==6.0.0',
        'pydantic==2.9.2',
        'pydantic-core==2.23.4',
        'python-dateutil==2.9.0.post0',
        'pytz==2024.2',
        'pyyaml==6.0.2',
        'rdkit==2024.3.5',
        'requests==2.32.3',
        'scipy==1.14.1',
        'six==1.16.0',
        'sympy==1.13.3',
        'torch==2.4.0',
        'tqdm==4.66.5',
        'triton==3.0.0',
        'typing-extensions==4.12.2',
        'tzdata==2024.2',
        'urllib3==2.2.3',
    ],
    entry_points={
        'console_scripts': [
            'bindingrmsd-inference=bindingrmsd.inference:main',
        ],
    },
    author='Jaemin Sim',
    author_email='sjm0775@snu.ac.kr',
    description='Protein-ligand Binding RMSD prediction method',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/eightmm/BindingRMSD',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: Apache Software License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.10',
)

